### ISSUE TITLE
[FABRIC] MC 1.20.1 - Some incompatibility leads to Inventory not opening

### ISSUE THREAD

**Issue by LokeYourC3PH** [blueberryperson5/mine-six-siege#1]
What the title says. There seems to be something, an incompatibility perhaps that leads to the inventory refusing to open. However, there's nothing in the logs, and so I am not sure what could cause it if anything at all, and so providing logs is meaningless. Is there anything you change about inventory opening?

**Comment by blix5** [comment]
It's because the tilt keys are by default set to Q and E, conflicting with the inventory and drop keys. I'll change these defaults to different keys that won't conflict with the default Minecraft keys. For now you can change your inventory key to something like 'I' and drop key to 'Y' if those are available, which is what I do.
